version: "3"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: barbearia
      POSTGRES_DB: barbearia
    ports:
      - 5435:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data